### ISSUE TITLE
Error: Unknown "fabric" SDK version "1.4.0"

### ISSUE THREAD

**Issue by HumeirFaroog** [hyperledger/caliper-benchmarks#135] opened 2020-12-30 14:09 UTC
Hello, I'm trying to  install caliper , when I come to  this step(npx caliper bind \
    --caliper-bind-sut fabric:1.4.0) I got this error  below
 (   I'm using:  Ubuntu 20.04
Fabric v1.4.0
nodejs v10.14.1
npm 6.13.4
docker 19.03.8& docker-compose v1.25.0)

2020.12.30-16:57:19.347 error [caliper] [bind] 	Unknown "fabric" SDK version "1.4.0"
Usage:
  caliper bind --caliper-bind-sut fabric:1.4 --caliper-bind-cwd ./ --caliper-bind-args="-g"

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform and its SDK to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Unknown "fabric" SDK version "1.4.0"
    at Function.handler (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/lib/lib/bindCommon.js:89:19)
    at Object.module.exports.handler (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/lib/bindCommand.js:49:41)

    at Object.runCommand (/home/humeyra/Documents/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/humeyra/Documents/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/home/humeyra/Documents/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/caliper.js:39:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

can  anyone help me  how can i solve it even, I  try all  the version of Fabric but nothing change?

**Comment by qii67** [comment] 2021-03-11 12:59
I change it to fabric:1.4 works, but i am facing another problem
```
caliper_1  | 2021.03.11-12:58:04.593 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: Error: Module "fabric-network" could not be loaded: Error: Cannot find module 'fs-extra'
caliper_1  | Searched paths: /home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/node_modules,/home/node/.npm-global/lib/node_modules,/home/node/.npm-global/node_modules,/home/node/node_modules,/home/node_modules,/node_modules
caliper_1  | Usage:
caliper_1  |  caliper launch manager --caliper-bind-sut fabric:1.4 [other options]
caliper_1  | 
caliper_1  | Options:
caliper_1  |   --help, -h           Show usage information  [boolean]
caliper_1  |   --version            Show version information  [boolean]
caliper_1  |   --caliper-bind-sut   The name and version of the platform to bind to  [string]
caliper_1  |   --caliper-bind-cwd   The working directory for performing the SDK install  [string]
caliper_1  |   --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
caliper_1  |   --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]
caliper_1  | 
caliper_1  | Error: Module "fabric-network" could not be loaded: Error: Cannot find module 'fs-extra'
caliper_1  | Searched paths: /home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/node_modules,/home/node/.npm-global/lib/node_modules,/home/node/.npm-global/node_modules,/home/node/node_modules,/home/node_modules,/node_modules
caliper_1  |     at Function.loadModule (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:118:19)
caliper_1  |     at Function.moduleIsInstalled (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:181:26)
caliper_1  |     at new FabricConnector (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/fabric-connector.js:63:26)
caliper_1  |     at CaliperEngine.connectorFactory [as adapterFactory] (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/connectorFactory.js:26:23)
caliper_1  |     at CaliperEngine.run (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/manager/caliper-engine.js:93:36)
caliper_1  |     at Function.handler (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:62:43)
caliper_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
workspace_caliper_1 exited with code 1
```

**Comment by MUKESHBADIGINENI** [comment] 2021-03-22 06:55
> Hello, I'm trying to install caliper , when I come to this step(npx caliper bind
> --caliper-bind-sut fabric:1.4.0) I got this error below
> ( I'm using: Ubuntu 20.04
> Fabric v1.4.0
> nodejs v10.14.1
> npm 6.13.4
> docker 19.03.8& docker-compose v1.25.0)
> 
> 2020.12.30-16:57:19.347 error [caliper] [bind] Unknown "fabric" SDK version "1.4.0"
> Usage:
> caliper bind --caliper-bind-sut fabric:1.4 --caliper-bind-cwd ./ --caliper-bind-args="-g"
> 
> Options:
> --help, -h Show usage information [boolean]
> --version Show version information [boolean]
> --caliper-bind-sut The name and version of the platform and its SDK to bind to [string]
> --caliper-bind-cwd The working directory for performing the SDK install [string]
> --caliper-bind-args Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter [string]
> --caliper-bind-file Yaml file to override default (supported) package versions when binding an SDK [string]
> 
> Error: Unknown "fabric" SDK version "1.4.0"
> at Function.handler (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/lib/lib/bindCommon.js:89:19)
> at Object.module.exports.handler (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/lib/bindCommand.js:49:41)
> 
> ```
> at Object.runCommand (/home/humeyra/Documents/node_modules/yargs/lib/command.js:240:40)
> at Object.parseArgs [as _parseArgs] (/home/humeyra/Documents/node_modules/yargs/yargs.js:1154:41)
> at Object.get [as argv] (/home/humeyra/Documents/node_modules/yargs/yargs.js:1088:21)
> at Object.<anonymous> (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/caliper.js:39:5)
> at Module._compile (internal/modules/cjs/loader.js:688:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
> at Module.load (internal/modules/cjs/loader.js:598:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
> ```
> 
> can anyone help me how can i solve it even, I try all the version of Fabric but nothing change?

I tried changing the version into "1.4" it runs, but after few seconds new set of errors were popped out.

![image](https://user-images.githubusercontent.com/37984445/111951425-9fba5280-8b1e-11eb-9ac8-f9cc70252757.png)

**Comment by CaixiangFan** [comment] 2021-04-28 23:12
> I change it to fabric:1.4 works, but i am facing another problem
> 
> ```
> caliper_1  | 2021.03.11-12:58:04.593 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: Error: Module "fabric-network" could not be loaded: Error: Cannot find module 'fs-extra'
> caliper_1  | Searched paths: /home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/node_modules,/home/node/.npm-global/lib/node_modules,/home/node/.npm-global/node_modules,/home/node/node_modules,/home/node_modules,/node_modules
> caliper_1  | Usage:
> caliper_1  |  caliper launch manager --caliper-bind-sut fabric:1.4 [other options]
> caliper_1  | 
> caliper_1  | Options:
> caliper_1  |   --help, -h           Show usage information  [boolean]
> caliper_1  |   --version            Show version information  [boolean]
> caliper_1  |   --caliper-bind-sut   The name and version of the platform to bind to  [string]
> caliper_1  |   --caliper-bind-cwd   The working directory for performing the SDK install  [string]
> caliper_1  |   --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
> caliper_1  |   --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]
> caliper_1  | 
> caliper_1  | Error: Module "fabric-network" could not be loaded: Error: Cannot find module 'fs-extra'
> caliper_1  | Searched paths: /home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/node_modules,/home/node/.npm-global/lib/node_modules,/home/node/.npm-global/node_modules,/home/node/node_modules,/home/node_modules,/node_modules
> caliper_1  |     at Function.loadModule (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:118:19)
> caliper_1  |     at Function.moduleIsInstalled (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:181:26)
> caliper_1  |     at new FabricConnector (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/fabric-connector.js:63:26)
> caliper_1  |     at CaliperEngine.connectorFactory [as adapterFactory] (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/connectorFactory.js:26:23)
> caliper_1  |     at CaliperEngine.run (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/manager/caliper-engine.js:93:36)
> caliper_1  |     at Function.handler (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:62:43)
> caliper_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
> workspace_caliper_1 exited with code 1
> ```

Hi, did you resolve it? I met the same problem.

**Comment by MUKESHBADIGINENI** [comment] 2021-04-29 01:59
Check the caliper version and SUT binding version, please refer the caliper documentation page for matching versions.
I suggest, docker installation is best for fixing the caliper issues, it will run Soo smooth and we can modify the content easily.

**Comment by qii67** [comment] 2021-04-29 02:04
> > I change it to fabric:1.4 works, but i am facing another problem
> > ```
> > caliper_1  | 2021.03.11-12:58:04.593 error [caliper] [cli-launch-manager] 	Unexpected error during benchmark execution: Error: Module "fabric-network" could not be loaded: Error: Cannot find module 'fs-extra'
> > caliper_1  | Searched paths: /home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/node_modules,/home/node/.npm-global/lib/node_modules,/home/node/.npm-global/node_modules,/home/node/node_modules,/home/node_modules,/node_modules
> > caliper_1  | Usage:
> > caliper_1  |  caliper launch manager --caliper-bind-sut fabric:1.4 [other options]
> > caliper_1  | 
> > caliper_1  | Options:
> > caliper_1  |   --help, -h           Show usage information  [boolean]
> > caliper_1  |   --version            Show version information  [boolean]
> > caliper_1  |   --caliper-bind-sut   The name and version of the platform to bind to  [string]
> > caliper_1  |   --caliper-bind-cwd   The working directory for performing the SDK install  [string]
> > caliper_1  |   --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
> > caliper_1  |   --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]
> > caliper_1  | 
> > caliper_1  | Error: Module "fabric-network" could not be loaded: Error: Cannot find module 'fs-extra'
> > caliper_1  | Searched paths: /home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/node_modules,/home/node/.npm-global/lib/node_modules/@hyperledger/node_modules,/home/node/.npm-global/lib/node_modules,/home/node/.npm-global/node_modules,/home/node/node_modules,/home/node_modules,/node_modules
> > caliper_1  |     at Function.loadModule (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:118:19)
> > caliper_1  |     at Function.moduleIsInstalled (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/common/utils/caliper-utils.js:181:26)
> > caliper_1  |     at new FabricConnector (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/fabric-connector.js:63:26)
> > caliper_1  |     at CaliperEngine.connectorFactory [as adapterFactory] (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/connectorFactory.js:26:23)
> > caliper_1  |     at CaliperEngine.run (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-core/lib/manager/caliper-engine.js:93:36)
> > caliper_1  |     at Function.handler (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:62:43)
> > caliper_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
> > workspace_caliper_1 exited with code 1
> > ```
> > 
> > ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)复制到剪切板
> 
> Hi, did you resolve it? I met the same problem.

Try `npm install --save fs-extra` firstly, you can find the solution [here](https://github.com/hyperledger/caliper/issues/374)

**Comment by plutomonth** [comment] 2021-09-23 09:20
> > Hello, I'm trying to install caliper , when I come to this step(npx caliper bind
> > --caliper-bind-sut fabric:1.4.0) I got this error below
> > ( I'm using: Ubuntu 20.04
> > Fabric v1.4.0
> > nodejs v10.14.1
> > npm 6.13.4
> > docker 19.03.8& docker-compose v1.25.0)
> > 2020.12.30-16:57:19.347 error [caliper] [bind] Unknown "fabric" SDK version "1.4.0"
> > Usage:
> > caliper bind --caliper-bind-sut fabric:1.4 --caliper-bind-cwd ./ --caliper-bind-args="-g"
> > Options:
> > --help, -h Show usage information [boolean]
> > --version Show version information [boolean]
> > --caliper-bind-sut The name and version of the platform and its SDK to bind to [string]
> > --caliper-bind-cwd The working directory for performing the SDK install [string]
> > --caliper-bind-args Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter [string]
> > --caliper-bind-file Yaml file to override default (supported) package versions when binding an SDK [string]
> > Error: Unknown "fabric" SDK version "1.4.0"
> > at Function.handler (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/lib/lib/bindCommon.js:89:19)
> > at Object.module.exports.handler (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/lib/bindCommand.js:49:41)
> > ```
> > at Object.runCommand (/home/humeyra/Documents/node_modules/yargs/lib/command.js:240:40)
> > at Object.parseArgs [as _parseArgs] (/home/humeyra/Documents/node_modules/yargs/yargs.js:1154:41)
> > at Object.get [as argv] (/home/humeyra/Documents/node_modules/yargs/yargs.js:1088:21)
> > at Object.<anonymous> (/home/humeyra/Documents/node_modules/@hyperledger/caliper-cli/caliper.js:39:5)
> > at Module._compile (internal/modules/cjs/loader.js:688:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
> > at Module.load (internal/modules/cjs/loader.js:598:32)
> > at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can anyone help me how can i solve it even, I try all the version of Fabric but nothing change?
> 
> I tried changing the version into "1.4" it runs, but after few seconds new set of errors were popped out.
> 
> ![image](https://user-images.githubusercontent.com/37984445/111951425-9fba5280-8b1e-11eb-9ac8-f9cc70252757.png)

I ran into the same problem using hyperledger/caliper docker, how to solve it?

**Comment by davidkel** [comment] 2022-01-17 11:13
duplicate of https://github.com/hyperledger/caliper/issues/1146

**Comment by davidkel** [comment] 2022-01-17 13:31
It looks like there are 2 different problems being reported here
1. module 'fs-extra' cannot be loaded when using docker image
2. build error on the bind command.

1 is covered by the caliper issue 1146 mentioned above
2. is due to using the wrong version of node. You have to use node 10 for caliper 0.4.x

**Closed** 2022-01-17 15:16 UTC
