### ISSUE TITLE
2org1peergoleveldb_kafka [caliper-flow] : Error: Couldn't create Channel 'mychannel'

### ISSUE THREAD

**Issue by tharindupr** [hyperledger/caliper-benchmarks#37] opened 2019-12-10 12:15 UTC
I was running the test benchmark on 2org1peergoleveldb_kafka/docker-compose.yaml configurations. Here's how I ran the benchmark.

`npx caliper benchmark run --caliper-benchconfig benchmarks/samples/fabric/marbles/config.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.0/2org1peergoleveldb_kafka/fabric-node.yaml --caliper-workspace ./`

**Error**
```
error [caliper] [caliper-flow] 	Error: Error: Couldn't create Channel 'mychannel': Orderer response indicated unsuccessful Channel 'mychannel' creation: SERVICE_UNAVAILABLE
    at Fabric._createChannels (/root/benchmarks/caliper-benchmarks/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:352:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I was using the network configuration as it is in the config_kafka. I'm not sure whether this is a bug or something I'm not doing correctly.

**Comment by aklenik** [comment] 2020-01-08 13:10
@tharindupr Service unavailable errors usually occur when your single machine can't handle the network size. A kafka-based Fabric network can be resource-demanding for a single machine. Additionally, make sure that your orderers started successfully (by inspecting the logs).
Without these details, debugging the problem is not really possible.

**Comment by SaadBinShahid** [comment] 2020-01-15 19:38
@tharindupr were you able to solve this? It sometimes happen when your previously run command is not exited properly. If you run the `end` command defined in docker-compose file [2org1peergoleveldb_kafka/fabric-node.yaml](https://github.com/hyperledger/caliper-benchmarks/blob/master/networks/fabric/fabric-v1.4.0/2org1peergoleveldb_kafka/fabric-node.yaml) explicitly. It should fix it.

```
caliper:
    blockchain: fabric
    command:
        start: export FABRIC_VERSION=1.4.0;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb_kafka/docker-compose.yaml up -d;sleep 10s
        end: docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb_kafka/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

```



```
docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb_kafka/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
```

**Comment by gaewcha** [comment] 2020-02-19 04:16
I faced the same error as yours. After checking the orderer container logs, it seems like orderers are not properly started when the joining command is executed. So my solution is execute the start command separately in the terminal
```
export FABRIC_VERSION=1.4.0;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb_kafka/docker-compose.yaml up -d
```
Then check whether the orderer containers are actually ready 
```
docker logs -f <orderer container>
```
In the start command in config file, you can simply change it to just echo out something
```
caliper:
    blockchain: fabric
    command:
        start: echo 'start'
        end: docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb_kafka/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
```


Hope it helps

**Comment by aklenik** [comment] 2020-02-28 08:44
@tharindupr @gaewcha Depending on the available resource, it might take some time for the orderers/peers to start. The `start` script in the network configuration file is there for convenience to easily spin up a local network that matches the topology of the configuration file. But this is not a requirement, Caliper can connect to an already running network. So possible workarounds:

1. Execute the start script content separately (from the workspace directory) and wait for the network to properly start. In this case, you can omit the start script entirely (no need for an echo).
2. Increase the sleep time at the end of the start script.

There's no fool-proof and general mechanism to wait for a remote service to be ready, so Caliper will not provide such a smart feature.

Since this is a Fabric-side problem, I'm closing this issue.

**Closed by aklenik** 2020-02-28 08:44 UTC
